In [3]:
import pandas as pd
import re
import os
import numpy as np
import pandas as pd
import pylab as P

In [4]:
path=os.path.join('/Users/pierregagliardi/DossierTravail/Programmation/PythonPath','Kaggle_Titanic','Dataset','train.csv')
df = pd.read_csv(path, header=0)
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 90.5+ KB

In [5]:
df.describe()

In [ ]:
df.head()

In [ ]:
df.Age.hist()

In [5]:
import numpy as np
import pandas as pd
import pylab as P
import re
import os

def retrieve_title(name):
    m = re.search(', ([A-Za-z ]+).', name)
    return m.group(1)

def numeric_title(title):
    titles={
        ('Ms','Mme', 'Mlle'):0,
        ('Capt', 'Don', 'Major', 'Sir'): 1,
        ('Dona', 'Lady', 'the Countess', 'Jonkheer'): 2,
        ('Col'):3,
        ('Dr'):4,
        ('Master'):5,
        ('Miss'):6,
        ('Mr'):7,
        ('Mrs'):8,
        ('Rev'):9
    }
    for (key,value) in titles.iteritems():
        if title in key:
            return value
            break

#Open up the csv file in to a Python object
path=os.path.join('/Users/pierregagliardi/DossierTravail/Programmation/PythonPath','Kaggle_Titanic','Dataset','train.csv')
df = pd.read_csv(path, header=0)

#Gender in numeric
df['Gender'] = df['Sex'].map( {'female': 0, 'male': 1} ).astype(int)

#Add column of titles
df['Title']=df['Name'].map(retrieve_title)
 
#Complete missing age values
titles = df['Title'].unique()
df['AgeFill'] = df['Age']
df['FamilySize'] = df['SibSp'] + df['Parch']

for title in titles:
    print "Average age of persons with title %s:"%(title)
    print "%d\n"%(df[df['Title']==title]['Age'].mean())
    df.loc[ (df.Age.isnull()) & (df.Title == title),'AgeFill'] = df[df['Title']==title]['Age'].mean()

df.loc[ (df.Age.isnull()) & (df.Title == title),'AgeFill'] = df[df['Title']==title]['Age'].mean()
df['Embarked_numeric'] = df['Embarked'].map( {'C': 0, 'S': 1, 'Q':2} ).astype(int)
df['Title_numeric'] = df['Title'].map( numeric_title ).astype(int)
df.loc[:,'AgeFill']=(df['AgeFill']-df['AgeFill'].mean())/df['AgeFill'].std()
df.loc[:,'Fare']=(df['Fare']-df['Fare'].mean())/df['Fare'].std()

df = df.drop(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked','Title'], axis=1)
df.head()

Average age of persons with title Mr:
32

Average age of persons with title Mrs:
35

Average age of persons with title Miss:
21

Average age of persons with title Master:
4

Average age of persons with title Don:
40

Average age of persons with title Rev:
43

Average age of persons with title Dr:
42

Average age of persons with title Mme:
24

Average age of persons with title Ms:
28

Average age of persons with title Major:
48

Average age of persons with title Lady:
48

Average age of persons with title Sir:
49

Average age of persons with title Mlle:
24

Average age of persons with title Col:
58

Average age of persons with title Capt:
70

Average age of persons with title the Countess:
33

Average age of persons with title Jonkheer:
38

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Gender,AgeFill,FamilySize,Embarked_numeric,Title_numeric
0,1,0,3,22,1,0,-0.502163,1,-0.584059,1,1,7
1,2,1,1,38,1,0,0.786404,0,0.621016,1,0,8
2,3,1,3,26,0,0,-0.488580,0,-0.282790,0,1,6
3,4,1,1,35,1,0,0.420494,0,0.395064,1,1,8
4,5,0,3,35,0,0,-0.486064,1,0.395064,0,1,7

In [10]:
df[df['Age'] > 60]

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Gender,AgeFill,FamilySize,Embarked_numeric,Title_numeric
33,34,0,2,66.0,0,0,-0.436762,1,2.729898,0,1,7
54,55,0,1,65.0,0,1,0.599174,1,2.654581,1,0,7
96,97,0,1,71.0,0,0,0.049302,1,3.106484,0,0,7
116,117,0,3,70.5,0,0,-0.492101,1,3.068825,0,2,7
170,171,0,1,61.0,0,0,0.026076,1,2.353312,0,1,7
252,253,0,1,62.0,0,0,-0.113782,1,2.428629,0,1,7
275,276,1,1,63.0,1,0,0.920727,0,2.503946,1,1,6
280,281,0,3,65.0,0,0,-0.492101,1,2.654581,0,2,7
326,327,0,3,61.0,0,0,-0.522538,1,2.353312,0,1,7
438,439,0,1,64.0,1,4,4.644393,1,2.579263,5,1,7
456,457,0,1,65.0,0,0,-0.113782,1,2.654581,0,1,7
483,484,1,3,63.0,0,0,-0.455125,0,2.503946,0,1,8
493,494,0,1,71.0,0,0,0.348134,1,3.106484,0,0,7
545,546,0,1,64.0,0,0,-0.124850,1,2.579263,0,1,7
555,556,0,1,62.0,0,0,-0.113782,1,2.428629,0,1,7
570,571,1,2,62.0,0,0,-0.436762,1,2.428629,0,1,7
625,626,0,1,61.0,0,0,0.002346,1,2.353312,0,1,7
630,631,1,1,80.0,0,0,-0.044356,1,3.784339,0,1,7
672,673,0,2,70.0,0,0,-0.436762,1,3.031167,0,1,7
745,746,0,1,70.0,1,1,0.780703,1,3.031167,2,1,1
829,830,1,1,62.0,0,0,0.961813,0,2.428629,0,0,8
851,852,0,3,74.0,0,0,-0.491598,1,3.332435,0,1,7

In [11]:
df['Cabin'].unique()

KeyError: 'Cabin'

KeyError: 'Cabin'